include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# Additional linting rules for production packages
linter:
  rules:
    # Package-specific rules
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    
    # Code quality rules
    avoid_print: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_const: true
    unnecessary_new: true
    use_build_context_synchronously: true
