name: flutter_chunked_upload
description: >
  A robust Flutter package for chunked file uploads with resume, progress tracking, queue management, and persistent storage. Supports pause, resume, cancel, and priority-based upload queue. Ideal for large file uploads in unreliable network conditions.
version: 1.0.0
homepage: https://github.com/Akshya15/flutter_chunked_upload
repository: https://github.com/Akshya15/flutter_chunked_upload

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.0
  connectivity_plus: ^6.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  path: ^1.9.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6


flutter:


